export const BOARD_ROLE_CREATOR = "CREATOR";
export const BOARD_ROLE_PENDING = "PENDING";
export const BOARD_ROLE_USER = "USER";

/*  */

export const CACHE_MANAGER_USER_ID = "CACHE_MANAGER_USER_ID";
export const CACHE_MANAGER_USER_USERNAME = "CACHE_MANAGER_USER_USERNAME";

export const CACHE_MANAGER_CARD_GET_BY_BOARD_ID = "CACHE_MANAGER_CARD_GET_BY_BOARD_ID";

export const CACHE_MANAGER_BOARD_GET_BY_ID = "CACHE_MANAGER_BOARD_GET_BY_ID";